### ISSUE TITLE
Listen to the feedback from the rabbit mq

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/ViSR#5]
update: 
following https://github.com/DiamondLightSource/bluesky-stomp/issues/15 this issue will be about another new deployment of the stomp -websocket service, not directly a change to ViSR code

**Comment by stan-dot** [comment]
update: this looks like it would be a microservice, might be under the blueapi repo or here as a subpackage for visr

**Comment by stan-dot** [comment]
update - decision with @callumforrester  to wait until this library is ready 
https://github.com/DiamondLightSource/bluesky-stomp

**Comment by callumforrester** [comment]
@stan-dot would you please also raise an issue in that library detailing your use case?

**Comment by stan-dot** [comment]
@callumforrester what is the earliest I can work on this? I'm happy to help with anything you need related to the bluesky-stomp if that'd smooth things out

**Comment by callumforrester** [comment]
@stan-dot it has been delayed by pydantic 2 issues, the hope is that we will be able to work on it next sprint.

**Comment by stan-dot** [comment]
theoretically just a callback could do it

**Comment by stan-dot** [comment]
first need to get the data out of the manta tbh

**Comment by stan-dot** [comment]
for data writing need to use this

https://github.com/DiamondLightSource/i22-bluesky/blob/fe8c692192fd597b94ab6bd19fbc0b0026249a5c/src/i22_bluesky/plans/linkam.py#L113-L114

**Comment by stan-dot** [comment]
tracking this elsewhere now
